# Generated by Django 5.0.6 on 2024-07-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emp_ponit_alter_emp_name_alter_emp_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='manam_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('val', models.CharField(max_length=100, null=True)),
                ('ponit', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
