# Generated by Django 5.0.6 on 2024-07-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_manam_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manam_upload',
        ),
    ]
