# Generated by Django 5.0.6 on 2024-07-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_manam_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='ponit',
            new_name='point',
        ),
    ]
