# Generated by Django 5.0.6 on 2024-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_ponit_emp_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='point',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='val',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
