# Generated by Django 5.0.6 on 2024-07-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_emp_phone_alter_emp_point_alter_emp_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='point',
        ),
    ]
